// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type EventDocumentDataSlicesSlice = ImageGridSlice

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Type field in *Event*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: WEDDING
   * - **API ID Path**: event.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<'WEDDING' | 'PRIVATE' | 'CORPORATE', 'filled'>

  /**
   * Thumbnail field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>

  /**
   * Title field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Credits field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Photo or other credits
   * - **API ID Path**: event.credits
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  credits: prismic.RichTextField

  /**
   * Slice Zone field in *Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventDocumentDataSlicesSlice> /**
   * Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<EventDocumentData>,
  'event',
  Lang
>

/**
 * Item in *Footer → Statements*
 */
export interface FooterDocumentDataStatementsItem {
  /**
   * Text field in *Footer → Statements*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.statements[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

type FooterDocumentDataSlicesSlice = SocialItemSlice | NavItemSlice

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Name field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField

  /**
   * Newsletter Input field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Email Address*
   * - **API ID Path**: footer.newsletter_input
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_input: prismic.KeyTextField

  /**
   * Newsletter CTA field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: SIGN UP
   * - **API ID Path**: footer.newsletter_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletter_cta: prismic.RichTextField

  /**
   * Newsletter Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Subscribe to our newsletter for planning resources, inspiration, and updates!
   * - **API ID Path**: footer.newsletter_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletter_text: prismic.RichTextField

  /**
   * Statements field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.statements[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  statements: prismic.GroupField<Simplify<FooterDocumentDataStatementsItem>>

  /**
   * Copyright field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: 2024 Two Perfect Events™ All rights reserved. Photo Credits / Terms & Privacy
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright: prismic.RichTextField

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<FooterDocumentData>,
  'footer',
  Lang
>

type MemberDocumentDataSlicesSlice = never

/**
 * Content for Member documents
 */
interface MemberDocumentData {
  /**
   * Image field in *Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: member.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * First Name field in *Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.first_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first_name: prismic.RichTextField

  /**
   * Last Name field in *Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.last_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  last_name: prismic.RichTextField

  /**
   * Pronouns field in *Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.pronouns
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pronouns: prismic.RichTextField

  /**
   * Title field in *Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Bio field in *Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField

  /**
   * Likes field in *Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.likes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  likes: prismic.RichTextField

  /**
   * Slice Zone field in *Member*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: member.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MemberDocumentDataSlicesSlice>
}

/**
 * Member document from Prismic
 *
 * - **API ID**: `member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<MemberDocumentData>,
  'member',
  Lang
>

type NavDocumentDataSlicesSlice = NavItemSlice

/**
 * Content for Nav documents
 */
interface NavDocumentData {
  /**
   * Name field in *Nav*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Name of the navigation list
   * - **API ID Path**: nav.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField

  /**
   * Slice Zone field in *Nav*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavDocumentDataSlicesSlice>
}

/**
 * Nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<NavDocumentData>,
  'nav',
  Lang
>

type PageDocumentDataSlicesSlice =
  | CallToActionSlice
  | ProfileSlice
  | ImageGridSlice
  | CalloutSlice
  | ContactSlice
  | AwardsSlice
  | TestimonialsSlice
  | ServicesSlice
  | BannerSlice
  | HeroImageSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PageDocumentData>,
  'page',
  Lang
>

type PortfolioDocumentDataSlicesSlice = EventsListSlice

/**
 * Content for Portfolio documents
 */
interface PortfolioDocumentData {
  /**
   * Title field in *Portfolio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Description field in *Portfolio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Slice Zone field in *Portfolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice> /**
   * Meta Description field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PortfolioDocumentData>,
  'portfolio',
  Lang
>

type PostDocumentDataSlicesSlice = never

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Slice Zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostDocumentDataSlicesSlice> /**
   * Meta Description field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PostDocumentData>,
  'post',
  Lang
>

export type AllDocumentTypes =
  | EventDocument
  | FooterDocument
  | MemberDocument
  | NavDocument
  | PageDocument
  | PortfolioDocument
  | PostDocument

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField

  /**
   * title field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * description field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * image field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *AlternateGrid → Items*
 */
export interface AlternateGridSliceDefaultItem {
  /**
   * title field in *AlternateGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * description field in *AlternateGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AlternateGridSliceDefaultPrimary>,
  Simplify<AlternateGridSliceDefaultItem>
>

/**
 * Primary content in *AlternateGrid → Image Right → Primary*
 */
export interface AlternateGridSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.imageRight.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField

  /**
   * title field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * description field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * image field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *AlternateGrid → Items*
 */
export interface AlternateGridSliceImageRightItem {
  /**
   * title field in *AlternateGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * description field in *AlternateGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Image Right variation for AlternateGrid Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageRight = prismic.SharedSliceVariation<
  'imageRight',
  Simplify<AlternateGridSliceImageRightPrimary>,
  Simplify<AlternateGridSliceImageRightItem>
>

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation = AlternateGridSliceDefault | AlternateGridSliceImageRight

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<'alternate_grid', AlternateGridSliceVariation>

/**
 * Primary content in *Awards → Items*
 */
export interface AwardsSliceDefaultItem {
  /**
   * Title field in *Awards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Logo field in *Awards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Subtitle field in *Awards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: If rating is provided this value is ignored.
   * - **API ID Path**: awards.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField

  /**
   * Rating field in *Awards → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: (Optional) 0-5, if provided subtitle is ignored.
   * - **API ID Path**: awards.items[].rating
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rating: prismic.NumberField

  /**
   * Link field in *Awards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for Awards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<AwardsSliceDefaultItem>
>

/**
 * Slice variation for *Awards*
 */
type AwardsSliceVariation = AwardsSliceDefault

/**
 * Awards Shared Slice
 *
 * - **API ID**: `awards`
 * - **Description**: Awards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardsSlice = prismic.SharedSlice<'awards', AwardsSliceVariation>

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceDefaultItem {
  /**
   * Title field in *Banner → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: WEDDINGS
   * - **API ID Path**: banner.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<BannerSliceDefaultItem>
>

/**
 * Primary content in *Banner → Simple → Primary*
 */
export interface BannerSliceSimplePrimary {
  /**
   * Text field in *Banner → Simple → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.simple.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Simple variation for Banner Slice
 *
 * - **API ID**: `simple`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceSimple = prismic.SharedSliceVariation<'simple', Simplify<BannerSliceSimplePrimary>, never>

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault | BannerSliceSimple

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<'banner', BannerSliceVariation>

/**
 * Item in *CallToAction → Default → Primary → Packages*
 */
export interface CallToActionSliceDefaultPrimaryPackagesItem {
  /**
   * Text field in *CallToAction → Default → Primary → Packages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.packages[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Image field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Description field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * CTA Link field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Redirect URL for CTA button
   * - **API ID Path**: call_to_action.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField

  /**
   * CTA Text field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Label for CTA button
   * - **API ID Path**: call_to_action.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_text: prismic.RichTextField

  /**
   * Packages field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.packages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  packages: prismic.GroupField<Simplify<CallToActionSliceDefaultPrimaryPackagesItem>>

  /**
   * Background field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Optionally select a background color.
   * - **API ID Path**: call_to_action.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<
    'ivory' | 'beige' | 'sienna' | 'blush' | 'coffee' | 'background' | 'foreground' | 'primary' | 'secondary' | 'text'
  >

  /**
   * Text Align field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: call_to_action.default.primary.text_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_align: prismic.SelectField<'center' | 'left' | 'right', 'filled'>
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *CallToAction → Image + Text → Primary*
 */
export interface CallToActionSliceImageTextPrimary {
  /**
   * Image field in *CallToAction → Image + Text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.imageText.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *CallToAction → Image + Text → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.imageText.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Description field in *CallToAction → Image + Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.imageText.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * CTA Link field in *CallToAction → Image + Text → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Redirect URL for CTA button
   * - **API ID Path**: call_to_action.imageText.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField

  /**
   * CTA Text field in *CallToAction → Image + Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Label for CTA button
   * - **API ID Path**: call_to_action.imageText.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_text: prismic.RichTextField

  /**
   * Background field in *CallToAction → Image + Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Optionally select a background color.
   * - **API ID Path**: call_to_action.imageText.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<
    'ivory' | 'beige' | 'sienna' | 'blush' | 'coffee' | 'background' | 'foreground' | 'primary' | 'secondary' | 'text'
  >

  /**
   * Text Align field in *CallToAction → Image + Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: call_to_action.imageText.primary.text_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_align: prismic.SelectField<'center' | 'left' | 'right', 'filled'>
}

/**
 * Image + Text variation for CallToAction Slice
 *
 * - **API ID**: `imageText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceImageText = prismic.SharedSliceVariation<
  'imageText',
  Simplify<CallToActionSliceImageTextPrimary>,
  never
>

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault | CallToActionSliceImageText

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<'call_to_action', CallToActionSliceVariation>

/**
 * Item in *Callout → Partners → Primary → Venues*
 */
export interface CalloutSlicePartnersPrimaryVenuesItem {
  /**
   * Name field in *Callout → Partners → Primary → Venues*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.partners.primary.venues[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField

  /**
   * Link field in *Callout → Partners → Primary → Venues*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional link to venue website or other url.
   * - **API ID Path**: callout.partners.primary.venues[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Primary content in *Callout → Default → Primary*
 */
export interface CalloutSliceDefaultPrimary {
  /**
   * Title field in *Callout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Body field in *Callout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField

  /**
   * Background field in *Callout → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<'background' | 'foreground' | 'primary' | 'secondary' | 'accent'>

  /**
   * Accents field in *Callout → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: callout.default.primary.accents
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  accents: prismic.BooleanField
}

/**
 * Default variation for Callout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSliceDefault = prismic.SharedSliceVariation<'default', Simplify<CalloutSliceDefaultPrimary>, never>

/**
 * Primary content in *Callout → Partners → Primary*
 */
export interface CalloutSlicePartnersPrimary {
  /**
   * Title field in *Callout → Partners → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.partners.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Background field in *Callout → Partners → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.partners.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<'background' | 'foreground' | 'primary' | 'secondary' | 'accent'>

  /**
   * Accents field in *Callout → Partners → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: callout.partners.primary.accents
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  accents: prismic.BooleanField

  /**
   * Venues field in *Callout → Partners → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.partners.primary.venues[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  venues: prismic.GroupField<Simplify<CalloutSlicePartnersPrimaryVenuesItem>>
}

/**
 * Partners variation for Callout Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSlicePartners = prismic.SharedSliceVariation<
  'partners',
  Simplify<CalloutSlicePartnersPrimary>,
  never
>

/**
 * Slice variation for *Callout*
 */
type CalloutSliceVariation = CalloutSliceDefault | CalloutSlicePartners

/**
 * Callout Shared Slice
 *
 * - **API ID**: `callout`
 * - **Description**: Callout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSlice = prismic.SharedSlice<'callout', CalloutSliceVariation>

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Image field in *Contact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<'default', Simplify<ContactSliceDefaultPrimary>, never>

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<'contact', ContactSliceVariation>

/**
 * Primary content in *CustomerLogos → Default → Primary*
 */
export interface CustomerLogosSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *CustomerLogos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  eyebrowHeadline: prismic.RichTextField

  /**
   * callToActionLabel field in *CustomerLogos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField

  /**
   * callToActionLink field in *CustomerLogos → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField
}

/**
 * Primary content in *CustomerLogos → Items*
 */
export interface CustomerLogosSliceDefaultItem {
  /**
   * image field in *CustomerLogos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * link field in *CustomerLogos → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for CustomerLogos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CustomerLogosSliceDefaultPrimary>,
  Simplify<CustomerLogosSliceDefaultItem>
>

/**
 * Slice variation for *CustomerLogos*
 */
type CustomerLogosSliceVariation = CustomerLogosSliceDefault

/**
 * CustomerLogos Shared Slice
 *
 * - **API ID**: `customer_logos`
 * - **Description**: CustomerLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSlice = prismic.SharedSlice<'customer_logos', CustomerLogosSliceVariation>

/**
 * Primary content in *EventsList → Default → Primary*
 */
export interface EventsListSliceDefaultPrimary {
  /**
   * Title field in *EventsList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Anchor Link field in *EventsList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Used to link or jump to this section within a page.
   * - **API ID Path**: events_list.default.primary.anchor_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anchor_link: prismic.KeyTextField
}

/**
 * Primary content in *EventsList → Items*
 */
export interface EventsListSliceDefaultItem {
  /**
   * Event field in *EventsList → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: events_list.items[].event
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  event: prismic.ContentRelationshipField<'event'>
}

/**
 * Default variation for EventsList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsListSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<EventsListSliceDefaultPrimary>,
  Simplify<EventsListSliceDefaultItem>
>

/**
 * Slice variation for *EventsList*
 */
type EventsListSliceVariation = EventsListSliceDefault

/**
 * EventsList Shared Slice
 *
 * - **API ID**: `events_list`
 * - **Description**: EventsList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsListSlice = prismic.SharedSlice<'events_list', EventsListSliceVariation>

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField

  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * callToActionLabel field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField

  /**
   * callToActionLink field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<'default', Simplify<HeroSliceDefaultPrimary>, never>

/**
 * Primary content in *Hero → Image Right → Primary*
 */
export interface HeroSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero.imageRight.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField

  /**
   * title field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * description field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * image field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * callToActionLabel field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField

  /**
   * callToActionLink field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField
}

/**
 * Image Right variation for Hero Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceImageRight = prismic.SharedSliceVariation<
  'imageRight',
  Simplify<HeroSliceImageRightPrimary>,
  never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceImageRight

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>

/**
 * Primary content in *HeroImage → Default → Primary*
 */
export interface HeroImageSliceDefaultPrimary {
  /**
   * Image field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Perferendis Repellendus Magnam Nemo
   * - **API ID Path**: hero_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Description field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Officia ex cupidatat et anim ut ullamco tempor laboris pariatur ex officia sint.
   * - **API ID Path**: hero_image.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * CTA Text field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: CLICK ME
   * - **API ID Path**: hero_image.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_text: prismic.RichTextField

  /**
   * CTA Link field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to another page
   * - **API ID Path**: hero_image.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField

  /**
   * Max Width field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: hero_image.default.primary.max_width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  max_width: prismic.SelectField<'default' | 'full' | 'tight' | 'loose', 'filled'>

  /**
   * Image Height field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: hero_image.default.primary.image_height
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_height: prismic.SelectField<'default' | 'short', 'filled'>

  /**
   * Padding field in *HeroImage → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: hero_image.default.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  padding: prismic.BooleanField
}

/**
 * Default variation for HeroImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroImageSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *HeroImage → Text Image → Primary*
 */
export interface HeroImageSliceTextImagePrimary {
  /**
   * Image field in *HeroImage → Text Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.textImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Title field in *HeroImage → Text Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Perferendis Repellendus Magnam Nemo
   * - **API ID Path**: hero_image.textImage.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Title Bottom field in *HeroImage → Text Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.textImage.primary.title_bottom
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_bottom: prismic.RichTextField

  /**
   * Description field in *HeroImage → Text Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Officia ex cupidatat et anim ut ullamco tempor laboris pariatur ex officia sint.
   * - **API ID Path**: hero_image.textImage.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * CTA Text field in *HeroImage → Text Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: CLICK ME
   * - **API ID Path**: hero_image.textImage.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_text: prismic.RichTextField

  /**
   * CTA Link field in *HeroImage → Text Image → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to another page
   * - **API ID Path**: hero_image.textImage.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField

  /**
   * Max Width field in *HeroImage → Text Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: default
   * - **API ID Path**: hero_image.textImage.primary.max_width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  max_width: prismic.SelectField<'default' | 'full' | 'tight' | 'loose', 'filled'>
}

/**
 * Text Image variation for HeroImage Slice
 *
 * - **API ID**: `textImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroImageSliceTextImage = prismic.SharedSliceVariation<
  'textImage',
  Simplify<HeroImageSliceTextImagePrimary>,
  never
>

/**
 * Slice variation for *HeroImage*
 */
type HeroImageSliceVariation = HeroImageSliceDefault | HeroImageSliceTextImage

/**
 * HeroImage Shared Slice
 *
 * - **API ID**: `hero_image`
 * - **Description**: HeroImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroImageSlice = prismic.SharedSlice<'hero_image', HeroImageSliceVariation>

/**
 * Primary content in *ImageGrid → Items*
 */
export interface ImageGridSliceDefaultItem {
  /**
   * Layout field in *ImageGrid → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: portrait
   * - **API ID Path**: image_grid.items[].layout
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  layout: prismic.SelectField<'portrait' | 'landscape' | 'square', 'filled'>

  /**
   * Image field in *ImageGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Caption field in *ImageGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.items[].caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField
}

/**
 * Default variation for ImageGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<ImageGridSliceDefaultItem>
>

/**
 * Slice variation for *ImageGrid*
 */
type ImageGridSliceVariation = ImageGridSliceDefault

/**
 * ImageGrid Shared Slice
 *
 * - **API ID**: `image_grid`
 * - **Description**: ImageGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSlice = prismic.SharedSlice<'image_grid', ImageGridSliceVariation>

/**
 * Primary content in *NavItem → Default → Primary*
 */
export interface NavItemSliceDefaultPrimary {
  /**
   * Name field in *NavItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Name of the link
   * - **API ID Path**: nav_item.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField

  /**
   * Link field in *NavItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the item
   * - **API ID Path**: nav_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Primary content in *NavItem → Items*
 */
export interface NavItemSliceDefaultItem {
  /**
   * Child Name field in *NavItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Name of the child link
   * - **API ID Path**: nav_item.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField

  /**
   * Child Link field in *NavItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the child item
   * - **API ID Path**: nav_item.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Child Description field in *NavItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Default variation for NavItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<NavItemSliceDefaultPrimary>,
  Simplify<NavItemSliceDefaultItem>
>

/**
 * Slice variation for *NavItem*
 */
type NavItemSliceVariation = NavItemSliceDefault

/**
 * NavItem Shared Slice
 *
 * - **API ID**: `nav_item`
 * - **Description**: NavItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavItemSlice = prismic.SharedSlice<'nav_item', NavItemSliceVariation>

/**
 * Primary content in *Profile → Items*
 */
export interface ProfileSliceDefaultItem {
  /**
   * Member field in *Profile → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.items[].member
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  member: prismic.ContentRelationshipField

  /**
   * Full Width field in *Profile → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: profile.items[].full_width
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  full_width: prismic.BooleanField
}

/**
 * Default variation for Profile Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProfileSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<ProfileSliceDefaultItem>
>

/**
 * Slice variation for *Profile*
 */
type ProfileSliceVariation = ProfileSliceDefault

/**
 * Profile Shared Slice
 *
 * - **API ID**: `profile`
 * - **Description**: Profile
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProfileSlice = prismic.SharedSlice<'profile', ProfileSliceVariation>

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Title field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional section title.
   * - **API ID Path**: services.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Description field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional description section text.
   * - **API ID Path**: services.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
  /**
   * Image field in *Services → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Link Text field in *Services → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Page to link to.
   * - **API ID Path**: services.items[].link_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  link_text: prismic.RichTextField

  /**
   * Link field in *Services → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * List field in *Services → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: List of items to detail out.
   * - **API ID Path**: services.items[].list
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list: prismic.RichTextField

  /**
   * Image Left field in *Services → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: services.items[].image_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_left: prismic.BooleanField
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ServicesSliceDefaultPrimary>,
  Simplify<ServicesSliceDefaultItem>
>

/**
 * Primary content in *Services → Main Services → Primary*
 */
export interface ServicesSliceMainServicesPrimary {
  /**
   * Title field in *Services → Main Services → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional section title.
   * - **API ID Path**: services.mainServices.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Description field in *Services → Main Services → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional description section text.
   * - **API ID Path**: services.mainServices.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceMainServicesItem {
  /**
   * Image field in *Services → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Link Text field in *Services → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Page to link to.
   * - **API ID Path**: services.items[].link_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  link_text: prismic.RichTextField

  /**
   * Link field in *Services → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Main Services variation for Services Slice
 *
 * - **API ID**: `mainServices`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceMainServices = prismic.SharedSliceVariation<
  'mainServices',
  Simplify<ServicesSliceMainServicesPrimary>,
  Simplify<ServicesSliceMainServicesItem>
>

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault | ServicesSliceMainServices

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<'services', ServicesSliceVariation>

/**
 * Primary content in *SocialItem → Default → Primary*
 */
export interface SocialItemSliceDefaultPrimary {
  /**
   * UTM field in *SocialItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: UTM string to append to each links for analytics (optional)
   * - **API ID Path**: social_item.default.primary.utm
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  utm: prismic.RichTextField
}

/**
 * Primary content in *SocialItem → Items*
 */
export interface SocialItemSliceDefaultItem {
  /**
   * Platform field in *SocialItem → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Yelp
   * - **API ID Path**: social_item.items[].platform
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  platform: prismic.SelectField<'Yelp' | 'Instagram' | 'Facebook' | 'TikTok' | 'Pinterest', 'filled'>

  /**
   * Link field in *SocialItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to social platform or profile.
   * - **API ID Path**: social_item.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for SocialItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SocialItemSliceDefaultPrimary>,
  Simplify<SocialItemSliceDefaultItem>
>

/**
 * Slice variation for *SocialItem*
 */
type SocialItemSliceVariation = SocialItemSliceDefault

/**
 * SocialItem Shared Slice
 *
 * - **API ID**: `social_item`
 * - **Description**: SocialItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialItemSlice = prismic.SharedSlice<'social_item', SocialItemSliceVariation>

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Quote field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField

  /**
   * Image field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Quote Position field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: testimonials.default.primary.quote_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  quote_position: prismic.SelectField<'left' | 'center' | 'right', 'filled'>

  /**
   * Background field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: background
   * - **API ID Path**: testimonials.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<'background' | 'foreground' | 'primary' | 'secondary' | 'accent', 'filled'>
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<'testimonials', TestimonialsSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      EventDocument,
      EventDocumentData,
      EventDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataStatementsItem,
      FooterDocumentDataSlicesSlice,
      MemberDocument,
      MemberDocumentData,
      MemberDocumentDataSlicesSlice,
      NavDocument,
      NavDocumentData,
      NavDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioDocumentDataSlicesSlice,
      PostDocument,
      PostDocumentData,
      PostDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceDefaultItem,
      AlternateGridSliceImageRightPrimary,
      AlternateGridSliceImageRightItem,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AlternateGridSliceImageRight,
      AwardsSlice,
      AwardsSliceDefaultItem,
      AwardsSliceVariation,
      AwardsSliceDefault,
      BannerSlice,
      BannerSliceDefaultItem,
      BannerSliceSimplePrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BannerSliceSimple,
      CallToActionSlice,
      CallToActionSliceDefaultPrimaryPackagesItem,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceImageTextPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceImageText,
      CalloutSlice,
      CalloutSliceDefaultPrimary,
      CalloutSlicePartnersPrimaryVenuesItem,
      CalloutSlicePartnersPrimary,
      CalloutSliceVariation,
      CalloutSliceDefault,
      CalloutSlicePartners,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      CustomerLogosSlice,
      CustomerLogosSliceDefaultPrimary,
      CustomerLogosSliceDefaultItem,
      CustomerLogosSliceVariation,
      CustomerLogosSliceDefault,
      EventsListSlice,
      EventsListSliceDefaultPrimary,
      EventsListSliceDefaultItem,
      EventsListSliceVariation,
      EventsListSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceImageRightPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceImageRight,
      HeroImageSlice,
      HeroImageSliceDefaultPrimary,
      HeroImageSliceTextImagePrimary,
      HeroImageSliceVariation,
      HeroImageSliceDefault,
      HeroImageSliceTextImage,
      ImageGridSlice,
      ImageGridSliceDefaultItem,
      ImageGridSliceVariation,
      ImageGridSliceDefault,
      NavItemSlice,
      NavItemSliceDefaultPrimary,
      NavItemSliceDefaultItem,
      NavItemSliceVariation,
      NavItemSliceDefault,
      ProfileSlice,
      ProfileSliceDefaultItem,
      ProfileSliceVariation,
      ProfileSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimary,
      ServicesSliceDefaultItem,
      ServicesSliceMainServicesPrimary,
      ServicesSliceMainServicesItem,
      ServicesSliceVariation,
      ServicesSliceDefault,
      ServicesSliceMainServices,
      SocialItemSlice,
      SocialItemSliceDefaultPrimary,
      SocialItemSliceDefaultItem,
      SocialItemSliceVariation,
      SocialItemSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault
    }
  }
}
