// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  alternate_grid: dynamic(() => import('./AlternateGrid')),
  awards: dynamic(() => import('./Awards')),
  banner: dynamic(() => import('./Banner')),
  call_to_action: dynamic(() => import('./CallToAction')),
  customer_logos: dynamic(() => import('./CustomerLogos')),
  hero: dynamic(() => import('./Hero')),
  hero_image: dynamic(() => import('./HeroImage')),
  nav_item: dynamic(() => import('./NavItem')),
  rich_text: dynamic(() => import('./RichText')),
  services: dynamic(() => import('./Services')),
  testimonials: dynamic(() => import('./Testimonials'))
}
