// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  alternate_grid: dynamic(() => import('./AlternateGrid')),
  awards: dynamic(() => import('./Awards')),
  banner: dynamic(() => import('./Banner')),
  call_to_action: dynamic(() => import('./CallToAction')),
  callout: dynamic(() => import('./Callout')),
  contact: dynamic(() => import('./Contact')),
  customer_logos: dynamic(() => import('./CustomerLogos')),
  events_list: dynamic(() => import('./EventsList')),
  hero: dynamic(() => import('./Hero')),
  hero_image: dynamic(() => import('./HeroImage')),
  image_grid: dynamic(() => import('./ImageGrid')),
  nav_item: dynamic(() => import('./NavItem')),
  profile: dynamic(() => import('./Profile')),
  services: dynamic(() => import('./Services')),
  social_item: dynamic(() => import('./SocialItem')),
  testimonials: dynamic(() => import('./Testimonials'))
}
